### PR TITLE
♻️ Major ODM update and refactoring

### PR DESCRIPTION
**Pull request by OomBen**

### CODE REVIEW

**Comment by ZoeLiebenberg** [comment]
Is there any way to get the SonarCloud to pass?

**Comment by OomBen** [comment]
> Is there any way to get the SonarCloud to pass?

Ye, I'll just remove those files, this isn't really used in production, only on my laptop

**Comment by OomBen** [comment]
@ZoeLiebenberg Please go ahead with the review. SonarCloud is grilling me on False positives here.

**Review by ZoeLiebenberg — APPROVED** [review]
Approved :)

**Pull request merged**
